user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # ================= Performance & Upload =================
    client_max_body_size 1000M;
    client_body_timeout 3000s;
    proxy_read_timeout 3000s;
    proxy_connect_timeout 3000s;
    proxy_send_timeout 3000s;

    # ================= HTTP → HTTPS =================
    server {
        listen 80;
        server_name api.choyxona.cognilabs.org;

        # Certbot challenge
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # ================= HTTPS =================
    server {
        listen 443 ssl http2;
        server_name api.choyxona.cognilabs.org;

        # 🔐 SSL (Certbot)
        ssl_certificate /etc/letsencrypt/live/api.choyxona.cognilabs.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.choyxona.cognilabs.org/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # ================= GZIP =================
        gzip on;
        gzip_types
            text/plain
            text/css
            application/json
            application/javascript
            text/xml
            application/xml
            application/xml+rss
            text/javascript;

        # ================= FASTAPI =================
        location / {
            proxy_pass http://web:8008;   # docker service name yoki 127.0.0.1:8008

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # ================= STATIC (agar bo‘lsa) =================
        location /static/ {
            alias /app/static/;
        }
    }
}
